// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO karr_agents (name, url, token, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, url, token, status, last_seen_at, created_at, updated_at
`

type CreateAgentParams struct {
	Name   string `json:"name"`
	Url    string `json:"url"`
	Token  string `json:"token"`
	Status string `json:"status"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (KarrAgent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Name,
		arg.Url,
		arg.Token,
		arg.Status,
	)
	var i KarrAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM karr_agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, url, token, status, last_seen_at, created_at, updated_at FROM karr_agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (KarrAgent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i KarrAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, name, url, token, status, last_seen_at, created_at, updated_at FROM karr_agents WHERE name = $1
`

func (q *Queries) GetAgentByName(ctx context.Context, name string) (KarrAgent, error) {
	row := q.db.QueryRow(ctx, getAgentByName, name)
	var i KarrAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, url, token, status, last_seen_at, created_at, updated_at FROM karr_agents ORDER BY name
`

func (q *Queries) ListAgents(ctx context.Context) ([]KarrAgent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KarrAgent{}
	for rows.Next() {
		var i KarrAgent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Token,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE karr_agents
SET name = $2, url = $3, token = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, url, token, status, last_seen_at, created_at, updated_at
`

type UpdateAgentParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Url   string      `json:"url"`
	Token string      `json:"token"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (KarrAgent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Token,
	)
	var i KarrAgent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE karr_agents
SET status = $2, last_seen_at = $3, updated_at = now()
WHERE id = $1
`

type UpdateAgentStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentStatus, arg.ID, arg.Status, arg.LastSeenAt)
	return err
}
