// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_registrations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRegistration = `-- name: ClaimRegistration :exec
UPDATE karr_agent_registrations
SET status = 'claimed', agent_id = $2, claimed_at = now()
WHERE id = $1
`

type ClaimRegistrationParams struct {
	ID      pgtype.UUID `json:"id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) ClaimRegistration(ctx context.Context, arg ClaimRegistrationParams) error {
	_, err := q.db.Exec(ctx, claimRegistration, arg.ID, arg.AgentID)
	return err
}

const cleanExpiredRegistrations = `-- name: CleanExpiredRegistrations :exec
UPDATE karr_agent_registrations
SET status = 'expired'
WHERE status = 'pending' AND expires_at <= now()
`

func (q *Queries) CleanExpiredRegistrations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredRegistrations)
	return err
}

const createAgentRegistration = `-- name: CreateAgentRegistration :one
INSERT INTO karr_agent_registrations (token_hash, label, status, expires_at)
VALUES ($1, $2, 'pending', now() + INTERVAL '1 hour')
RETURNING id, token_hash, label, status, agent_id, created_at, claimed_at, expires_at
`

type CreateAgentRegistrationParams struct {
	TokenHash string `json:"token_hash"`
	Label     string `json:"label"`
}

func (q *Queries) CreateAgentRegistration(ctx context.Context, arg CreateAgentRegistrationParams) (KarrAgentRegistration, error) {
	row := q.db.QueryRow(ctx, createAgentRegistration, arg.TokenHash, arg.Label)
	var i KarrAgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Label,
		&i.Status,
		&i.AgentID,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteRegistration = `-- name: DeleteRegistration :exec
DELETE FROM karr_agent_registrations WHERE id = $1
`

func (q *Queries) DeleteRegistration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegistration, id)
	return err
}

const getPendingRegistration = `-- name: GetPendingRegistration :one
SELECT id, token_hash, label, status, agent_id, created_at, claimed_at, expires_at FROM karr_agent_registrations
WHERE token_hash = $1 AND status = 'pending' AND expires_at > now()
`

func (q *Queries) GetPendingRegistration(ctx context.Context, tokenHash string) (KarrAgentRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistration, tokenHash)
	var i KarrAgentRegistration
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Label,
		&i.Status,
		&i.AgentID,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listRegistrations = `-- name: ListRegistrations :many
SELECT id, token_hash, label, status, agent_id, created_at, claimed_at, expires_at FROM karr_agent_registrations
ORDER BY created_at DESC
`

func (q *Queries) ListRegistrations(ctx context.Context) ([]KarrAgentRegistration, error) {
	rows, err := q.db.Query(ctx, listRegistrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KarrAgentRegistration{}
	for rows.Next() {
		var i KarrAgentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Label,
			&i.Status,
			&i.AgentID,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
