// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO karr_environments (project_id, agent_id, name, image, gpu, env, mounts, command)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, agent_id, name, image, container_id, status, gpu, env, mounts, command, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
	Name      string      `json:"name"`
	Image     string      `json:"image"`
	Gpu       bool        `json:"gpu"`
	Env       []byte      `json:"env"`
	Mounts    []byte      `json:"mounts"`
	Command   []byte      `json:"command"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (KarrEnvironment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.AgentID,
		arg.Name,
		arg.Image,
		arg.Gpu,
		arg.Env,
		arg.Mounts,
		arg.Command,
	)
	var i KarrEnvironment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.Name,
		&i.Image,
		&i.ContainerID,
		&i.Status,
		&i.Gpu,
		&i.Env,
		&i.Mounts,
		&i.Command,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM karr_environments WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, agent_id, name, image, container_id, status, gpu, env, mounts, command, created_at, updated_at FROM karr_environments WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id pgtype.UUID) (KarrEnvironment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i KarrEnvironment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.Name,
		&i.Image,
		&i.ContainerID,
		&i.Status,
		&i.Gpu,
		&i.Env,
		&i.Mounts,
		&i.Command,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project_id, agent_id, name, image, container_id, status, gpu, env, mounts, command, created_at, updated_at FROM karr_environments ORDER BY created_at DESC
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]KarrEnvironment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KarrEnvironment{}
	for rows.Next() {
		var i KarrEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.Name,
			&i.Image,
			&i.ContainerID,
			&i.Status,
			&i.Gpu,
			&i.Env,
			&i.Mounts,
			&i.Command,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByAgent = `-- name: ListEnvironmentsByAgent :many
SELECT id, project_id, agent_id, name, image, container_id, status, gpu, env, mounts, command, created_at, updated_at FROM karr_environments WHERE agent_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEnvironmentsByAgent(ctx context.Context, agentID pgtype.UUID) ([]KarrEnvironment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KarrEnvironment{}
	for rows.Next() {
		var i KarrEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.Name,
			&i.Image,
			&i.ContainerID,
			&i.Status,
			&i.Gpu,
			&i.Env,
			&i.Mounts,
			&i.Command,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, agent_id, name, image, container_id, status, gpu, env, mounts, command, created_at, updated_at FROM karr_environments WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]KarrEnvironment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KarrEnvironment{}
	for rows.Next() {
		var i KarrEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.Name,
			&i.Image,
			&i.ContainerID,
			&i.Status,
			&i.Gpu,
			&i.Env,
			&i.Mounts,
			&i.Command,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentContainerID = `-- name: UpdateEnvironmentContainerID :exec
UPDATE karr_environments
SET container_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateEnvironmentContainerIDParams struct {
	ID          pgtype.UUID `json:"id"`
	ContainerID string      `json:"container_id"`
}

func (q *Queries) UpdateEnvironmentContainerID(ctx context.Context, arg UpdateEnvironmentContainerIDParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentContainerID, arg.ID, arg.ContainerID)
	return err
}

const updateEnvironmentStatus = `-- name: UpdateEnvironmentStatus :exec
UPDATE karr_environments
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateEnvironmentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateEnvironmentStatus(ctx context.Context, arg UpdateEnvironmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentStatus, arg.ID, arg.Status)
	return err
}
