// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type KarrAgent struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	Token      string             `json:"token"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type KarrEnvironment struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Name        string             `json:"name"`
	Image       string             `json:"image"`
	ContainerID string             `json:"container_id"`
	Status      string             `json:"status"`
	Gpu         bool               `json:"gpu"`
	Env         []byte             `json:"env"`
	Mounts      []byte             `json:"mounts"`
	Command     []byte             `json:"command"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type KarrProject struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
